version: '3.8'
services:
  lerobot-test:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile-dev
      args:
        # 这里需要替换为自己的实际代理信息，或者注释掉
        PROXY: http://192.168.50.48:7890
        XXXX_TAG: XXXX_TAG
    volumes:
      # 这里需要替换为自己的实际映射路径
      - ..:/app    
      - F:/.cache:/root/.cache    
    command: sleep infinity
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      # wandb的配置，key可在这里获取https://wandb.ai/authorize
      WANDB_BASE_URL: https://api.wandb.ai
      WANDB_MODE: online
      WANDB_API_KEY: 614df134f7e9e9f4e7b13e899adab4e704ca74a6
      WANDB_USERNAME: samge
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    network_mode: bridge
    shm_size: 40g
    ports:
      - "0.0.0.0:17872:7860"